rule extract_sco_sequences:
    """Extract single-copy ortholog sequences for ingroup species."""
    input: "results/orthofinder/output"
    output: directory("results/phylo/sco_fastas")
    conda: "../envs/phylo.yaml"
    script: "../scripts/extract_sco.py"

rule concat_and_tree:
    """Build species tree from single-copy orthologs."""
    input: "results/phylo/sco_fastas"
    output:
        tree="results/phylo/concat_tree.treefile",
        concord="results/phylo/concord.cf.tree"
    params:
        model=config["iqtree"]["model"],
        bb=config["iqtree"]["bootstrap"]
    threads: config["threads"]
    conda: "../envs/phylo.yaml"
    shell:
        """
        # Orthogroup ids are regenerated by every OrthoFinder run, so a stale
        # OG0000123 is a different gene set. Never resume across runs.
        rm -rf results/phylo/alignments results/phylo/trimmed results/phylo/gene_trees
        mkdir -p results/phylo/alignments results/phylo/trimmed results/phylo/gene_trees

        for fa in results/phylo/sco_fastas/*.fa; do
            og=$(basename $fa .fa)
            if [ ! -f results/phylo/trimmed/$og.trim ]; then
                mafft --auto $fa > results/phylo/alignments/$og.aln 2>/dev/null
                trimal -in results/phylo/alignments/$og.aln \
                    -out results/phylo/trimmed/$og.trim -automated1 2>/dev/null || true
            fi
        done

        # Remove alignments too short for IQ-TREE (< 50 amino acids)
        for f in results/phylo/trimmed/*.trim; do
            cols=$(awk '/^[^>]/{{print length; exit}}' "$f")
            if [ "$cols" -lt 50 ]; then
                rm -f "$f"
            fi
        done

        NTRIM=$(ls results/phylo/trimmed/*.trim 2>/dev/null | wc -l)
        echo "Trimmed alignments after filtering: $NTRIM"

        # One tree per locus, {threads} at a time. Each is tiny (4 taxa) so
        # parallelism comes from running many at once rather than threading
        # each one. Sequentially this step took ~3 h for 9,000 loci.
        ls results/phylo/trimmed/*.trim | \
        xargs -P {threads} -I TRIMFILE sh -c '
            og=$(basename TRIMFILE .trim)
            iqtree -s TRIMFILE -m MFP -bb 1000 -nt 1 \
                --prefix results/phylo/gene_trees/$og -quiet 2>/dev/null || true
        '

        cat results/phylo/gene_trees/*.treefile > results/phylo/all_gene_trees.nwk 2>/dev/null || true

        iqtree -p results/phylo/trimmed/ \
            -m {params.model} -bb {params.bb} -nt {threads} \
            --prefix results/phylo/concat_tree -quiet

        iqtree -t results/phylo/concat_tree.treefile \
            --gcf results/phylo/all_gene_trees.nwk \
            -p results/phylo/trimmed/ \
            --scf 100 --prefix results/phylo/concord -quiet -nt {threads} || \
            cp results/phylo/concat_tree.treefile {output.concord}
        """
